version: '3.3'

services:
  redmine:
    image: sameersbn/redmine:4.0.4
    restart: always
    environment:
      - TZ=Europe/Berlin

      - DB_ADAPTER=mysql2
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=redmine
      - DB_PASS=redmine
      - DB_NAME=redmine

      - REDMINE_PORT=80
      - REDMINE_HTTPS=false
      - REDMINE_RELATIVE_URL_ROOT=
      - REDMINE_SECRET_TOKEN=secret

      - REDMINE_SUDO_MODE_ENABLED=false
      - REDMINE_SUDO_MODE_TIMEOUT=15

      - REDMINE_CONCURRENT_UPLOADS=2

      - SMTP_ENABLED=true
      - SMTP_METHOD=smtp
      - SMTP_DOMAIN=
      - SMTP_HOST=
      - SMTP_PORT=587
      - SMTP_USER=
      - SMTP_PASS=
      - SMTP_STARTTLS=true
      - SMTP_AUTHENTICATION=:login

      - IMAP_ENABLED=false
      - IMAP_HOST=imap.gmail.com
      - IMAP_PORT=993
      - IMAP_USER=mailer@example.com
      - IMAP_PASS=password
      - IMAP_SSL=true
      - IMAP_INTERVAL=30
    volumes:
      - ./data:/home/redmine/data
    labels:
      - traefik.enable=true
      - traefik.redmine.frontend.rule=Host:pms.5-anker.com
    depends_on:
      - db

  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=redmine
      - MYSQL_DATABASE=redmine
      - MYSQL_USER=redmine
