version: '3.3'

services:
  owncloud:
    image: owncloud/server
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
      - redis
    environment:
      - OWNCLOUD_DOMAIN=cloud.5-anker.com
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=owncloud
      - OWNCLOUD_DB_PASSWORD=owncloud
      - OWNCLOUD_DB_HOST=db
      - OWNCLOUD_ADMIN_USERNAME=admin
      - OWNCLOUD_ADMIN_PASSWORD=admin
      - OWNCLOUD_MYSQL_UTF8MB4=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=redis
    volumes:
      - ./data:/mnt/data
    labels:
      - traefik.enable=true
      - traefik.owncloud.frontend.rule=Host:cloud.5-anker.com
      - traefik.owncloud.port=8080

  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=owncloud
      - MYSQL_DATABASE=owncloud
      - MYSQL_USER=owncloud

  redis:
    image: redis
    restart: always
    volumes:
      - ./redis:/var/lib/redis
