version: '3.3'

services:
  nextcloud:
    image: nextcloud:apache
    restart: always
    volumes:
      - ./data:/var/www/html
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    depends_on:
      - db
      - redis
    labels:
      - traefik.enable=true
      - traefik.nextcloud.frontend.rule=Host:cloud.5-anker.com
      - traefik.nextcloud.port=80

  nextcloud-cron:
    image: nextcloud:apache
    restart: always
    volumes:
      - ./data:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  redis:
    image: redis
    restart: always
