version: "3"
services:
  typo3:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./data/fileadmin:/var/www/html/fileadmin
      - ./data/typo3conf:/var/www/html/typo3conf
      - ./data/uploads:/var/www/html/uploads
      - ./data/typo3temp:/var/www/html/typo3temp
  database:
    image: mysql:5.7
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - "MYSQL_USER=${MYSQL_USER:-typo3}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD:-typo3}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE:-typo3}"
      - "MYSQL_ROOT_PASSWORD=root"
