version: '3.3'

services:
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./runner.toml:/etc/gitlab-runner/config.toml
