version: "3.5"

services:
  wordpress:
    image: wordpress:php8.0-fpm-alpine
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        define('DISABLE_WP_CRON', true );
    volumes:
      - ./wordpress:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
    external_links:
      - db
    networks:
      - wordpress
      - db

  nginx:
    image: nginx
    restart: unless-stopped
    volumes:
      - ./wordpress:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - wordpress
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`example.com`)"
      - "traefik.http.routers.wordpress.tls.certresolver=myhttpchallenge"
      - "traefik.http.routers.wordpress.entrypoints=websecure"
      - "traefik.http.routers.wordpress.tls=true"

  scheduler:
    image: willfarrell/crontab
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./cron.json:/opt/crontab/config.json
    environment:
      - LOG_FILE=/dev/null
    networks:
      - wordpress

  memcached:
    image: memcached
    restart: unless-stopped
    networks:
      - wordpress

networks:
  wordpress:
  db:
    external: true
  traefik:
    external: true
