version: '3.5'

services:
    wordpress:
        build: .
        volumes:
        - ./wordpress:/var/www/html

    nginx:
        image: pagespeed/nginx-pagespeed
        volumes:
        - ./mysite.template:/etc/nginx/conf.d/mysite.template
        - ./wordpress:/var/www/html
        - ./mysite.template:/etc/nginx/conf.d/default.conf
        - ./conf:/etc/nginx/custom
        - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
        - "8080:80"
        environment:
        - NGINX_HOST=foobar.com
        - NGINX_PORT=80
        # command: /bin/sh -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

    mariadb:
        image: mariadb
        environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=wordpress
        volumes:
        - ./db:/var/lib/mysql

    memcached:
        image: memcached
